theme: jekyll-theme-minimal
title: [Personal Homepage of Xin Du]
description: [Hello there! Hope you have fun getting to know me!]
logo: [https://github.com/NotDX/notdx/blob/main/1.JPG]
show_downloads: ["false"]
